#!/usr/bin/env bash
# Bundle the ordered control-plane manifests in deploy/ into a single file so the
# whole stack installs with one `kubectl apply -f install.yaml`.
#
# Usage:
#   ./hack/gen-install.sh [output]            # local image names, default install.yaml
#   IMAGE_REGISTRY=ghcr.io/<owner> IMAGE_TAG=1.2.3 ./hack/gen-install.sh
#
# The deploy/NN-*.yaml prefixes encode dependency order (namespaces → CRD → RBAC
# → MySQL → storage → operator → apiserver → ui). The tenant sample CR is NOT
# included; create WordPressSite resources after the CRD is established.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="${1:-$ROOT/install.yaml}"
REG="${IMAGE_REGISTRY:-}"
TAG="${IMAGE_TAG:-latest}"

header="# Generated by hack/gen-install.sh — DO NOT EDIT BY HAND.
# Single-file install of the WordPress Manager control plane:
#   kubectl apply -f install.yaml
# Regenerate with: ./hack/gen-install.sh"

body="$(
  for f in "$ROOT"/deploy/[0-9]*.yaml; do
    echo '---'
    cat "$f"
    echo
  done
)"

if [ -n "$REG" ]; then
  body="$(printf '%s' "$body" | sed \
    -e "s#image: wordpress-manager/operator:latest#image: ${REG}/wordpress-manager-operator:${TAG}#" \
    -e "s#image: wordpress-manager/apiserver:latest#image: ${REG}/wordpress-manager-apiserver:${TAG}#" \
    -e "s#image: wordpress-manager/ui:latest#image: ${REG}/wordpress-manager-ui:${TAG}#")"
fi

printf '%s\n%s\n' "$header" "$body" > "$OUT"
echo "wrote $OUT (registry='${REG:-local}', tag='${TAG}')"
