//go:build !ignore_autogenerated

// Code generated by controller-gen conventions. Hand-maintained for this scaffold.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func (in *WordPressSite) DeepCopyInto(out *WordPressSite) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *WordPressSite) DeepCopy() *WordPressSite {
	if in == nil {
		return nil
	}
	out := new(WordPressSite)
	in.DeepCopyInto(out)
	return out
}

func (in *WordPressSite) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *WordPressSiteList) DeepCopyInto(out *WordPressSiteList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		l := make([]WordPressSite, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&l[i])
		}
		out.Items = l
	}
}

func (in *WordPressSiteList) DeepCopy() *WordPressSiteList {
	if in == nil {
		return nil
	}
	out := new(WordPressSiteList)
	in.DeepCopyInto(out)
	return out
}

func (in *WordPressSiteList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *WordPressSiteSpec) DeepCopyInto(out *WordPressSiteSpec) {
	*out = *in
	if in.Aliases != nil {
		out.Aliases = append([]string(nil), in.Aliases...)
	}
	if in.Replicas != nil {
		r := *in.Replicas
		out.Replicas = &r
	}
	in.Resources.DeepCopyInto(&out.Resources)
	out.Storage = in.Storage
	out.Database = in.Database
	out.TLS = in.TLS
	if in.IngressAnnotations != nil {
		m := make(map[string]string, len(in.IngressAnnotations))
		for k, v := range in.IngressAnnotations {
			m[k] = v
		}
		out.IngressAnnotations = m
	}
	if in.Env != nil {
		l := make([]corev1.EnvVar, len(in.Env))
		for i := range in.Env {
			in.Env[i].DeepCopyInto(&l[i])
		}
		out.Env = l
	}
}

func (in *WordPressSiteSpec) DeepCopy() *WordPressSiteSpec {
	if in == nil {
		return nil
	}
	out := new(WordPressSiteSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *WordPressSiteStatus) DeepCopyInto(out *WordPressSiteStatus) {
	*out = *in
	if in.Conditions != nil {
		l := make([]metav1.Condition, len(in.Conditions))
		for i := range in.Conditions {
			in.Conditions[i].DeepCopyInto(&l[i])
		}
		out.Conditions = l
	}
}

func (in *WordPressSiteStatus) DeepCopy() *WordPressSiteStatus {
	if in == nil {
		return nil
	}
	out := new(WordPressSiteStatus)
	in.DeepCopyInto(out)
	return out
}
